@extends('layouts.Nav')




@section('page')
<i class="fas fa-user"></i> Update Events
@endsection

@section('path')
Users / New User
@endsection





@section('content')
<form method="post"  action="{{route('UpdateEvents1')}}" enctype= "multipart/form-data"  style="font-size: 15px">
  {{ csrf_field() }}

<div class="container-fluid" id="container-wrapper">



<div class="msg">

</div>


          <div class="row mb-3">
  

           
            <!-- Pie Chart -->
            <div class="col-xl-4 col-lg-5">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between text-light" style="background-color: #6B80FB" >
                  <h6 class="m-0 font-weight-bold "><i class="fas fa-images"></i> Change profile</h6>
                 
                </div>
                <div class="card-body" >

<br>
<div class="form-group" style="margin-bottom: -40px">
<div class="profile-pic">
  <label class="-label" for="file">
    <span class="glyphicon glyphicon-camera"></span>
    <span><i class="fas fa-edit"></i></span>
  </label>
  <input  id="file" type="file" name="image" onchange="loadFile(event)"/>
  <img src="{{asset('/storage/images/Events/'.$users[0]->image)}}" id="output" width="200" />
</div>
<center><Span class="ErrImage feed">
  @error('image')
{{$message}}
@enderror 
</Span></center><br>
     </div>
      </div>

<div class="card-footer text-center" style="background-color: #6B80FB">
  <a class="btn btn-danger" id="Remove" onclick="RemoveFile(event)" style="display: none"><span style="color:white;" style="width: 20px"><i class="fas fa-trash-alt"></i></span></a>
    </div>  
  </div>



 </div>






 <!-- Area Chart -->
            <div class="col-xl-8 col-lg-7">
                  <?php  if(isset($_REQUEST['rslt'])){ ?>
                             <div class="alert alert-success" role="alert">
<B>Success</B> Events Information has been updated</div>
                <?php } else{ } ?>
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between text-light" style="background-color: #6B80FB">
                  <h6 class="m-0 font-weight-bold">Events Information : <span class="badge bg-warning" id="RefU" style="color: white"> <?php echo $users[0]->Reference; ?> </span></h6>
                </div>
                <div class="card-body">
                  

  <div class="form-row">
    <div class="col-md-12 mb-1">
            <label for="Ref">Reference:  <span style="color: red">*</span>   (A reference is pre-generated by the system for the new user.)</label>

<input type="text" class="form-control " name="Ref" id="Ref" value="<?php echo $users[0]->Reference; ?>" readonly>
</div></div>

<br>
  <div class="form-row">
    <div class="col-md mb">
      <label for="Title">Title <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('Title') is-invalid @enderror" name="Title" id="Title" placeholder="" value="<?php echo $users[0]->E_title; ?>" >
      <div class="ErrName feed">
       
@error('Title')
{{$message}}
@enderror 
      </div>
    </div>
   

</div>

<br>

  <div class="form-row">

   <div class="col-md mb-1">
      <label for="About">About <span style="color: red">*</span></label>
      <textarea type="textarea" class="form-control @error('About') is-invalid @enderror" name="About" id="About" ><?php echo $users[0]->about; ?></textarea>
      <div class="ErrTel feed">
@error('About')
{{$message }}
@enderror
      </div>
    </div>

   <div class="col-md mb-1">
      <label for="Location">Location <span style="color: red">*</span></label>
      <textarea  class="form-control @error('Location') is-invalid @enderror" name="Location" id="Location" ><?php echo $users[0]->Location; ?></textarea>
      <div class="ErrTel feed">
@error('Location')
{{$message }}
@enderror
      </div>
    </div>
  </div>
<br>


         
                 


  <div class="form-row">
 
    <div class="col-md mb-2">
      <label for="date">date/Time (Starting at )</label>
      <input type="datetime-local" class="form-control @error('date') is-invalid @enderror" name="date" id="date" value="<?php echo $users[0]->date; ?>">
      <div class="ErrOccupation feed">
@error('date')
{{$message }}
@enderror
      </div>
    </div>


  </div>



         <div class="form-row">


    <div class="col-md-4 mb-2">
      <label for="Duration">Duration <span style="color: red">*</span></label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend3"><B>Hours</B></span>
        </div>
        <input type="number" class="form-control @error('Duration') is-invalid @enderror" name="Duration" id="Duration" aria-describedby="inputGroupPrepend3" value="<?php echo $users[0]->duration; ?>" maxlength="1">
      </div>
<Span class="ErrEmail feed">
  @error('Duration')
{{$message }}
@enderror</Span>
    </div>

  </div>




<hr>
<center><button class="btn" id="save" style="width: 100px;background-color: #1270fc;color: white" type="submit"><i class="fas fa-plus-square"></i> Save</button>
 <a href="{{route('product')}}" style="width: 100px;" class="btn btn-danger"><i class="fas fa-arrow-left"></i> Back</a></center>




                </div>

<div class="card-footer text-center" style="background-color: #6B80FB">
      
    </div>  </div>
 </div>


              </div>
            </div>















</div>


                    </form>

  <button type="button" class="btn btn-primary" id="showdata" data-toggle="modal" data-target="#notif" ></button>

<script type="text/javascript">


</script>
@endsection
