@extends('layouts.Nav')




@section('page')
<i class="fas fa-user"></i> Add User Form
@endsection

@section('path')
Users / New User
@endsection





@section('content')
<?php $random = 'RA-'.rand(0,1).''.rand();?>
<form method="post"  action="{{route('AddUserUpload')}}" enctype= "multipart/form-data" id="Add" style="font-size: 13px">
  {{ csrf_field() }}

<div class="container-fluid" id="container-wrapper">



<div class="msg">

</div>


          <div class="row mb-3">
  

           
            <!-- Pie Chart -->
            <div class="col-xl-4 col-lg-5">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between text-light" style="background-color: #6B80FB">
                  <h6 class="m-0 font-weight-bold "><i class="fas fa-images"></i> Upload User Profile Picture</h6>
                 
                </div>
                <div class="card-body" >

<br>
<div class="form-group" style="margin-bottom: -40px">
<div class="profile-pic">
  <label class="-label" for="file">
    <span class="glyphicon glyphicon-camera"></span>
    <span><i class="fas fa-edit"></i></span>
  </label>
  <input  id="file" type="file" name="image" onchange="loadFile(event)"/>
  <img src="https://us.123rf.com/450wm/thesomeday123/thesomeday1231712/thesomeday123171200009/91087331-default-avatar-profile-icon-for-male-grey-photo-placeholder-illustrations-vector.jpg?ver=6" id="output" width="200" />
</div>
<center><Span class="ErrImage feed"></Span></center><br>
     </div>
      </div>

<div class="card-footer text-center" style="background-color: #6B80FB">
  <a class="btn btn-danger" id="Remove" onclick="RemoveFile(event)" style="display: none"><span style="color:white;" style="width: 20px"><i class="fas fa-trash-alt"></i></span></a>
    </div>  
  </div>



 </div>






 <!-- Area Chart -->
            <div class="col-xl-8 col-lg-7">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between text-light" style="background-color: #6B80FB">
                  <h6 class="m-0 font-weight-bold">General Information Form</h6>
                </div>
                <div class="card-body">
 <?php
if(isset($msg)){
  ?>
<div class="alert alert-warning" id="success-alert">
  <button type="button" class="close" data-dismiss="alert">x</button>
  <strong>Alert! </strong> <?php echo $msg; ?>
</div>

<?php
}
else{
};
?>

  <div class="form-row">
    <div class="col-md-12 mb-1">
            <label for="Name">Reference:  <span style="color: red">*</span>   (A reference is pre-generated by the system for the new user.)</label>
<a onclick="RefreshReference()" style="float: right"><i class="fas fa-sync-alt" style="color: lightgreen"></i></a>
<input type="text" class="form-control " name="Ref" id="Ref" value="<?php echo $random?>" readonly>
</div></div>

  <div class="form-row">
    <div class="col-md-8 mb-2">
      <label for="Name">Full Name <span style="color: red">*</span></label>
      <input type="text" class="form-control @error('Name') is-invalid @enderror" name="Name" id="Name" placeholder="" value="{{ old('Name') }}" >
      <div class="ErrName feed">
       
@error('Name')
{{$message}}
@enderror 
      </div>
    </div>


</div>

  <div class="form-row">

   <div class="col-md-6 mb-2">
      <label for="Tel">Tel <span style="color: red">*</span></label>
      <input type="tel" class="form-control @error('Tel') is-invalid @enderror" name="Tel" id="Tel" placeholder="" value="{{old('Tel')}}">
      <div class="ErrTel feed">
@error('Tel')
{{$message }}
@enderror
      </div>
    </div>

    <div class="col-md-6 mb-2">
      <label for="Privilege">Privilege <span style="color: red">*</span></label>
      <select class="form-control @error('Privilege') is-invalid @enderror" name="Privilege" id="Privilege" placeholder="" value="{{old('Privilege')}}">        
<option value="Member">Member</option>
<option value="Admin">Admin</option>
      </select>
      <div class="ErrPriv feed">
@error('Privilege')
{{$message }}
@enderror
      </div>
    </div>

  </div>

  <div class="form-row">
 
    <div class="col-md-12 mb-2">
      <label for="Graduation">Address</label>
      <input type="tel" class="form-control @error('Address') is-invalid @enderror" name="Address" id="Address" placeholder="" value="{{old('Address')}}">

      <div class="ErrOccupation feed">
@error('Address')
{{$message }}
@enderror
      </div>
    </div>


  </div>

           <br>    
                 
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between text-info">
                  <h6 class="m-0 font-weight-bold">Login Information</h6>
                </div>
                <br>

         <div class="form-row">
    <div class="col-md-12 mb-2">
      <label for="Email">Email <span style="color: red">*</span></label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend3">@</span>
        </div>
        <input type="text" class="form-control @error('Email') is-invalid @enderror" name="Email" id="Email" placeholder="" aria-describedby="inputGroupPrepend3" value="{{old('Email')}}">
      </div>
<Span class="ErrEmail feed">
  @error('Email')
{{$message }}
@enderror</Span>
    </div>
  </div>


    <div class="form-row">
    <div class="col-md-6 mb-2">
 <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
      <label for="password">Password <span style="color: red">*</span></label>
      <input type="password" class="form-control @error('Password') is-invalid @enderror" name="Password" id="Password" placeholder="" >
      <div class="ErrPassword feed">
@error('Password')
{{$message }}
@enderror
      </div>
    </div>
    </div>
    <div class="col-md-6 mb-2">
        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
      <label for="password-confirm">Confirm Password <span style="color: red">*</span></label>
      <input type="password" class="form-control @error('Password') is-invalid @enderror" id="password-confirm"  name="password_confirmation" aria-describedby="passwordHelp" placeholder="" >
      <div>
      </div>
        <!--Please provide a valid state.-->
      </div>
    </div>
  </div>

<hr>
<center><button class="btn" id="save" style="width: 100px;background-color: #1270fc;color: white" type="submit"><i class="fas fa-plus-square"></i> Save</button>
 <a href="{{route('UserConsultation')}}" style="width: 100px;" class="btn btn-danger"><i class="fas fa-arrow-left"></i> Back</a></center>




                </div>

<div class="card-footer text-center" style="background-color: #6B80FB">
      
    </div>  </div>
 </div>


              </div>
            </div>















</div>


                    </form>

  <button type="button" class="btn btn-primary" id="showdata" data-toggle="modal" data-target="#exampleModalCenter" style="visibility: hidden"></button>

<script type="text/javascript">


</script>
@endsection
